Skip to content
This repository
Search
Pull requests
Issues
Marketplace
Gist
 @alanmarksp
 Sign out
 Watch 31
  Star 751
 Fork 116 thyrlian/AwesomeValidation
 Code  Issues 4  Pull requests 0  Projects 0  Wiki Insights 
Branch: master Find file Copy pathAwesomeValidation/.travis.yml
755f004  4 days ago
@thyrlian thyrlian Update Travis config
2 contributors @thyrlian @nisrulz
RawBlameHistory    
35 lines (27 sloc)  774 Bytes
sudo: false

language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo yes | android update sdk --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION --no-ui --force

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest