language: android
jdk: oraclejdk8
sudo: required

android:
  components: # Cookbooks version: https://github.com/travis-ci/travis-cookbooks/tree/9c6cd11
    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
    - build-tools-25.0.3 # Match build-tools version used in build.gradle
    - platform-tools # Update platform-tools to revision 25.0.3+
    - tools # Update tools from revision 24.4.1 to 25.2.5

env:
  global:
    - API=25 # Android API level 25 by default
    - TAG=google_apis # Google APIs by default, alternatively use default
    - ABI=armeabi-v7a # ARM ABI v7a by default
    - QEMU_AUDIO_DRV=none # Disable emulator audio to avoid warning
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - TOOLS=${ANDROID_HOME}/tools # PATH order matters, exists more than one emulator script
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

before_install:
  - export EMULATOR="system-images;android-${API};${TAG};${ABI}" # Used to install/create emulator
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning

install:
  # List and delete unnecessary components to free space
  - $ANDROID_HOME/tools/bin/sdkmanager --list || true
  - $ANDROID_HOME/tools/bin/sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"

  # Update sdk tools to latest version and install/update components
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "tools"
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25" # Latest platform required by SDK tools
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-${API}" # Android platform required by emulator
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "$EMULATOR" # Install emulator system image
  # Create and start emulator
  - echo no | avdmanager create avd -n acib -k "$EMULATOR" -f --abi "$ABI" --tag "$TAG"
  - emulator -avd acib -engine classic -no-window -verbose -qemu -m 512 &

before_script:
  # Wait for emulator fully-booted and disable animations
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck

after_script:
  - cat ${TRAVIS_BUILD_DIR}/*/build/outputs/androidTest-results/connected/*