#!/bin/bash

A=$(adb shell getprop init.svc.bootanim | tr -d '\r')
while [ "$A" != "1" ]; do
    echo "$A"
    echo "Waiting for emulator"
    sleep 5
    A=$(adb shell getprop init.svc.bootanim | tr -d '\r')
    adb shell getprop | grep completed
done